services:
  - type: web
    name: telegram-accounting-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
    autoDeploy: true
