services:
  - type: web
    name: telegram-accounting-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 bot:app"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: OWNER_ID
        sync: false
      - key: USE_WEBHOOK
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.9"
    autoDeploy: true
